/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.laq.quanlycovid.view;

import com.laq.quanlycovid.controller.ThemSPController;
import com.laq.quanlycovid.dao.DBConnect;
import com.laq.quanlycovid.dao.QueryForProduct;
import com.laq.quanlycovid.model.SanPham;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoàng Lân
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
//    SanPham tableModel = new SanPham();
//    List<SanPham> list = new ArrayList<SanPham>();
//    Connection conn;
//    PreparedStatement ptmt;
//    ResultSet rs;
    
    public AddProduct(SanPham sp) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        ThemSPController controller = new ThemSPController(them, huy, ID, ten, dongia, dvtinh, hinhanh);
        controller.setView(sp);
        controller.setEvent();
        
        
        
//        conn = DBConnect.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ten1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dongia1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dvtinh1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hinhanh1 = new javax.swing.JTextField();
        huy1 = new javax.swing.JButton();
        them1 = new javax.swing.JButton();
        ten2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dongia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dvtinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hinhanh = new javax.swing.JTextField();
        huy = new javax.swing.JButton();
        them = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Thêm Sản Phẩm");

        jLabel6.setText("Thêm Sản Phẩm");

        jLabel7.setText("Tên Sản Phẩm: ");

        ten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Đơn Giá:");

        dongia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongia1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Đơn Vị Tính:");

        dvtinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvtinh1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Hình Ảnh: ");

        hinhanh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinhanh1ActionPerformed(evt);
            }
        });

        huy1.setText("HỦY");

        them1.setText("THÊM");
        them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dongia1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ten1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvtinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hinhanh1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(huy1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(them1)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(51, 51, 51)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ten1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dongia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dvtinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hinhanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huy1)
                    .addComponent(them1))
                .addGap(42, 42, 42))
        );

        ten2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm Sản Phẩm");

        jLabel1.setText("Thêm Sản Phẩm");

        jLabel2.setText("Tên Sản Phẩm: ");

        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        jLabel3.setText("Đơn Giá:");

        dongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongiaActionPerformed(evt);
            }
        });

        jLabel4.setText("Đơn Vị Tính:");

        dvtinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvtinhActionPerformed(evt);
            }
        });

        jLabel5.setText("Hình Ảnh: ");

        hinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinhanhActionPerformed(evt);
            }
        });

        huy.setText("HỦY");

        them.setText("THÊM");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel11.setText("ID Sản Phẩm");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dongia, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvtinh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(huy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(them)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dvtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huy)
                    .addComponent(them))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//    private void getData(){
//        list = QueryForProduct.getList();
//        tableModel.setRowCount(0);
//        for(SanPham sp: list){
//            tableModel.addRow(new Object[]{
//                sp.getIdSP(),
//                sp.getTenSP(),
//                sp.getDonGiaSP(),
//                sp.getDvTinh(),
//                sp.getHinhAnh()                              
//            });
//        }
//    }
    
    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenActionPerformed

    private void dongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dongiaActionPerformed

    private void dvtinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvtinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dvtinhActionPerformed

    private void hinhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hinhanhActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
//        conn = DBConnect.getConnection();
//        String sql = "insert into SANPHAM(idSP, tenSP, donGia, dvTinh, hinhAnh) values (?,?,?,?,?)";
//        try{
//            ptmt = conn.prepareStatement(sql);
//            ptmt.setString(1, ID.getText());
//            ptmt.setString(2, ten.getText());
//            ptmt.setString(3, dongia.getText());
//            ptmt.setString(4, dvtinh.getText());
//            ptmt.setString(5, hinhanh.getText());
//            
//            ptmt.execute();
//            JOptionPane.showMessageDialog(null, "Thêm thành công");
//        }catch(SQLException e){
//            JOptionPane.showMessageDialog(null, e);
//        }
//        String idSP = ID.getText();
//        if(idSP.isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm không thể trống");
//            return;
//        }
//        
//        String tenSP = ten.getText();
//        if(tenSP.isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Tên sản phẩm không thể trống");
//            return;
//        }
//        
//        String dvTinh = dvtinh.getText();
//        if(dvTinh.isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Đơn vị tính không thể trống");
//            return;
//        }
//        
//        String hinhAnh = hinhanh.getText();
//        if(hinhAnh.isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Hình ảnh không thể trống");
//            return;
//        }
//        
//        try{
//            int donGia = Integer.parseInt(dongia.getText());
//            if(checkIdSP()){
//                SanPham sp = new SanPham(idSP, tenSP, donGia, dvTinh, hinhAnh);
//                QueryForProduct.insert(sp);
//            }else{
//                JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm không thể trùng");
//            }
//            
//        }catch(NumberFormatException e){
//            JOptionPane.showMessageDialog(rootPane, "Nhập giá tiền");
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(rootPane, "Lỗi:" + e);
//        }
//        getData();
    }//GEN-LAST:event_themActionPerformed
//    private boolean checkIdSP() {
//        for (SanPham sp : list) {
//            if (sp.getIdSP().trim().equalsIgnoreCase(ID.getText().trim())) {
//                return false;
//            }
//        }
//        return true;
//    }
    
    
        
    private void ten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ten1ActionPerformed

    private void dongia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dongia1ActionPerformed

    private void dvtinh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvtinh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dvtinh1ActionPerformed

    private void hinhanh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinhanh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hinhanh1ActionPerformed

    private void them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_them1ActionPerformed

    private void ten2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ten2ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProduct().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField dongia;
    private javax.swing.JTextField dongia1;
    private javax.swing.JTextField dvtinh;
    private javax.swing.JTextField dvtinh1;
    private javax.swing.JTextField hinhanh;
    private javax.swing.JTextField hinhanh1;
    private javax.swing.JButton huy;
    private javax.swing.JButton huy1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ten;
    private javax.swing.JTextField ten1;
    private javax.swing.JTextField ten2;
    private javax.swing.JButton them;
    private javax.swing.JButton them1;
    // End of variables declaration//GEN-END:variables
}
