/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.laq.quanlycovid.view;
import com.laq.quanlycovid.controller.SanPhamController;
import com.laq.quanlycovid.dao.DBConnect;
import com.laq.quanlycovid.model.SanPham;
import com.laq.quanlycovid.dao.SanPhamDAOImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Envy
 */
public class ProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductsJPanel
     */


    public ProductsJPanel() {
        initComponents();
//        setLocationRelativeTo(null);
        SanPhamController controller = new SanPhamController(jpnTable, jbtAdd, jtfSearch);
        controller.setDataToTable();
        controller.setEvent();
        
    }

//    public void close(){
//        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
//    }
    
//    public void setRecordsToTable(){
//        try{
//            Connection conn = DBConnect.getConnection();
//            PreparedStatement pst = conn.prepareStatement("select * from SANPHAM");
//            ResultSet rs = pst.executeQuery();
//            
//            while(rs.next()){
//                String id = rs.getString("idSP");
//                String ten = rs.getString("tenSP");
//                int dongia = rs.getInt("donGiaSP");
//                String dvtinh = rs.getString("dvTinh");
//                String hinhanh = rs.getString("hinhAnh");
//                
//                Object[] obj = {id, ten, dongia, dvtinh, hinhanh};
//                model = (DefaultTableModel) jtProduct.getModel();
//                model.addRow(obj);
//            }
//        }catch(SQLException e){
//            e.printStackTrace();
//        }
//    }
//    
//    public void getData(){
//        list = SanPhamDAOImpl.getList();
//        tableModel.setRowCount(0);
//        for(SanPham sp: list){
//            tableModel.addRow(new Object[]{
//                sp.getIdSP(),
//                sp.getTenSP(),
//                sp.getDonGiaSP(),
//                sp.getDvTinh(),
//                sp.getHinhAnh()                              
//            });
//        }
//    }
//    
//    public void Search(String str){
//        setRecordsToTable();
//        model = (DefaultTableModel) jtProduct.getModel();
//        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
//        jtProduct.setRowSorter(trs);
//        trs.setRowFilter(RowFilter.regexFilter(str));      
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new java.awt.Panel();
        jtfSearch = new javax.swing.JTextField();
        jbtAdd = new javax.swing.JButton();
        jpnTable = new javax.swing.JPanel();

        jpnRoot.setPreferredSize(new java.awt.Dimension(607, 512));

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });

        jbtAdd.setText("Thêm");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTableLayout = new javax.swing.GroupLayout(jpnTable);
        jpnTable.setLayout(jpnTableLayout);
        jpnTableLayout.setHorizontalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnTableLayout.setVerticalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtfSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAdd;
    private java.awt.Panel jpnRoot;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
